# Generated by Django 2.0.1 on 2018-03-11 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('order', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('order', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.TextField(help_text="Don't forget to change OPEN to UC in the url.")),
                ('caption', models.CharField(blank=True, max_length=600)),
                ('order', models.PositiveSmallIntegerField()),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apollo.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(blank=True, max_length=256)),
                ('column2', models.CharField(blank=True, max_length=256)),
                ('column3', models.CharField(blank=True, max_length=256)),
                ('order', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=128)),
                ('order', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='resumerow',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apollo.ResumeSection'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apollo.Image'),
        ),
    ]
